services:
  web-app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    restart: always
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DB_PORT=5432
    command: >
      sh -c "python manage.py migrate && python manage.py loaddata fixtures/sample && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
volumes:
  database:
