# Generated by Django 4.2.2 on 2023-06-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vacation_rentals.rentalproperty')),
            ],
        ),
    ]
