# Generated by Django 4.2.2 on 2023-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_rentals', '0002_rentalbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperty',
            options={'verbose_name_plural': 'Rental properties'},
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='rental',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='rental',
            field=models.ManyToManyField(blank=True, related_name='booked', to='vacation_rentals.rentalproperty'),
        ),
    ]
